version: '2'
services:

### elasticsearch
  elasticsearch:
    image: elasticsearch:5.2.1
    ports:
      - "9200:9200"
    environment:
      - cluster.name=logstash-images
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK

